{
 "title": "[Loki] Pod Logs",
 "tags": [
  "loki",
  "logs",
  "kubernetes"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "query": "label_values(namespace)" },
   {
    "name": "pod",
    "query": "label_values({namespace=~\"$namespace\"}, pod)"
   },
   {
    "name": "container",
    "query": "label_values({namespace=~\"$namespace\", pod=~\"$pod\"}, container)"
   },
   { "name": "search" }
  ]
 },
 "panels": [
  { "title": "Log Volume", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Log Volume by Pod",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=~\"$namespace\", pod=~\"$pod\"}[$__interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Error Log Volume",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=~\"$namespace\", pod=~\"$pod\"} |~ \"(?i)(error|exception|fatal|panic)\"[$__interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Pod Logs",
   "type": "logs",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "{namespace=~\"$namespace\", pod=~\"$pod\", container=~\"$container\"} |~ \"$search\""
    }
   ]
  }
 ]
}